# Carga automática de colores de Pywal
include ~/.cache/wal/colors-sway

# --- SwayFX (requiere swayfx) ---
corner_radius 10
shadows enabled
shadow_color $color4

# --- Gaps y Bordes ---
gaps inner 3
gaps outer 3
#smart_gaps on
smart_borders on
default_border pixel 3
default_floating_border pixel 3

# --- Colores de ventanas (Pywal) ---
client.focused          $color4 $color4 $foreground $color4 $color4
client.focused_inactive $color0 $color0 $foreground $color0 $color0
client.unfocused        $color0 $color0 $foreground $color0 $color0
client.urgent           $color1 $color1 $foreground $color1 $color1

# Fuente global
font pango:JetBrains Mono 10
font pango:Monocraft 12

blur enable
blur_passes 3
blur_radius 5


