
# for_window [app_id="brave"] opacity 0.44
# for_window [class="Google-chrome"] opacity 0.9
# for_window [class=".*"] opacity 0.66

# Aquí puedes añadir reglas específicas:
# for_window [app_id="foot"] resize set 900 600
# for_window [title=".*GIMP.*"] floating enable
# assign [app_id="firefox"] 2
